### ISSUE TITLE
Form & password validation on signup

### ISSUE THREAD

**Issue by james-oldfield** [journalisttoolbox/journalisttoolbox-front-end#27]
- Passwords need to match else signup need not be granted.
- Perhaps some kind of colour-conditional for invalid fields like the create form field

**Comment by nevosegal** [comment]
important to mention that the validation is already happening and the API returns the right error messages - we only need to display them to the user.

**Comment by james-oldfield** [comment]
Will work on this today :+1:

**Comment by nevosegal** [comment]
Note that I only return the errors from the API in the login - but it should be very straightforward to do the same thing on signup

**Comment by nevosegal** [comment]
@James-Oldfield is this solved?

**Comment by james-oldfield** [comment]
The issues raised here are, although we still need to check for unavailable usernames

**Comment by nevosegal** [comment]
ok I'll keep this open.

**Comment by nevosegal** [comment]
Still need to check for matching passwords before signup
