### ISSUE TITLE
Is 3 characters on tool search too many?

### ISSUE THREAD

**Issue by james-oldfield** [journalisttoolbox/journalisttoolbox-front-end#31]
Having the search only trigger after 3 characters completely removes any ability to find any tools with names of length 1-3.. Just a thought. Perhaps we need to refactor search element.

**Comment by nevosegal** [comment]
Yes - I mentioned this last time we met. We should keep a regular submit along with the three letters auto-search.

**Comment by nevosegal** [comment]
Opened issue #40
