### ISSUE TITLE
Allow to search by a string shorter than 3 characters

### ISSUE THREAD

**Issue by nevosegal** [journalisttoolbox/journalisttoolbox-front-end#40]

**Comment by PedroQuijadaLeyton** [comment]
now it accept any length of string

**Comment by nevosegal** [comment]
How did you implement this? Changing the threshold from 3 to 1 characters is not a good idea in my opinion. This means that every time someone starts typing something the search results will initially display ALL of the tools in our database (because effectively a single character appears everywhere). We should re-enable the search button / clicking 'enter' to search instead (when there is less then 3 characters).

**Comment by nevosegal** [comment]
@PedroQuijadaLeyton ?

**Comment by PedroQuijadaLeyton** [comment]
I put a brief delay of 5 milliseconds to the search and it display the result no matter how long the string is, it is working fine but for a big number of tools it will eventually overload the database. As you said, we can implement the enter key button to search for less than 3 characters.
