### ISSUE TITLE
Create [Logged out]

### ISSUE THREAD

**Issue by chrishutchinson** [journalisttoolbox/journalisttoolbox-front-end#84]
Below are all when logged out.

Two things here:

1) The 'restricted' message when you click 'Create' in the menu is a bit harsh, it'd be better if this could be a gentler message with some onboarding, explaining why the user needs to sign up, and what they get for doing so. I can explain further and / or provide an example if necessary.

2) The current error message has a typo: "Please loginorsignup to continue.", should be "login or signup" with spaces.

<img width="583" alt="Restricted Area message" src="https://cloud.githubusercontent.com/assets/1573022/11443554/f1c9d1fe-9515-11e5-9327-3fa4bdfba843.png">

**Comment by james-oldfield** [comment]
Opinions on this solution?

![image](https://cloud.githubusercontent.com/assets/7990316/11638369/91b4b9f8-9d1e-11e5-8bbc-04c5f7ae01ea.png)

**Comment by chrishutchinson** [comment]
@James-Oldfield: Much better! Might be worth us looking into some additional wording there explaining why a dev might want to create an account and post a tool.

Happy to continue the discussion of this one in Slack.

**Comment by nevosegal** [comment]
OK, what do you think about this:
**Please login to continue**
If you are a developer and you would like to have your tool featured on newsroom.tools, please _login_ or _signup_ to continue.
