### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by chrishutchinson** [journalisttoolbox/journalisttoolbox-front-end#88]
While pretty good on the most part, it needs some work on the featured tool list. We should also look to create a flyout / dropdown menu in the navbar.

<img width="392" alt="Mobile view" src="https://cloud.githubusercontent.com/assets/1573022/11443638/8b1f004a-9516-11e5-8e3a-17163f4fc530.png">

**Comment by nevosegal** [comment]
Definitely a point worth working on, however not all the elements of semantic UI are mobile friendly, so this could take some time. We are currently working with semantic UI v1 and I think v2 is much better in the sense.
